name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/BFYOC' # set this to the path to your web app project, defaults to the repository root
    
jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
#- name: Install dependencies
    #  run: dotnet restore
   # - name: Build
    #  run: dotnet build --configuration Release --no-restore
    
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
